### ISSUE TITLE
Safepaste.org stopped working

### ISSUE THREAD

**Issue by Destroyer** [jeaye/safepaste#2]
https://safepaste.org/js/main.min.js 404

**Comment by jeaye** [comment]
Thanks for pointing this out. Looks like `main.min.js` isn't being packaged anymore; I'm thinking this must've been a boot change. Working on it.

**Comment by jeaye** [comment]
Ok, didn't find a quick fix and NixOS, which hosts safepaste.org, hasn't updated boot in a year. So, something else must've updated which broke this. I'll need to look more into it.

**Comment by jeaye** [comment]
I've pinpointed the issue to a ring version update. Curious that ring would affect boot's jar building, but I've reverted that update for now and I've the latest to https://safepaste.org (which looks to be working just fine now!).

Thanks again.
